/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 truck.gltf 
Author: Max (https://sketchfab.com/Max-5532)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/truck-daf-cf-75310-2f2ced3e54f24b4f8bee695e3261bd30
Title: Truck DAF CF 75.310
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('../src/components/3dmodels/truck/truck.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="DAF_CF_75_pt5c4dfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Termin��" position={[31.505, 14.582, 27.059]}>
                  <group name="Essui_glace_2" position={[-56.744, 32.516, 361.257]}>
                    <mesh name="Essui_glace_2_Barre_0" geometry={nodes.Essui_glace_2_Barre_0.geometry} material={materials.Barre} />
                  </group>
                  <group name="Essuis_glace_1" position={[79.101, 32.536, 359.81]} rotation={[-0.049, 0.014, -0.041]}>
                    <mesh name="Essuis_glace_1_Barre_0" geometry={nodes.Essuis_glace_1_Barre_0.geometry} material={materials.Barre} />
                  </group>
                  <group name="Porte_avant_droite" position={[-191.831, -9.193, 342.127]}>
                    <mesh name="Porte_avant_droite_Cr_Exterieur_0" geometry={nodes.Porte_avant_droite_Cr_Exterieur_0.geometry} material={materials.Cr_Exterieur} />
                    <mesh name="Porte_avant_droite_Retro_0" geometry={nodes.Porte_avant_droite_Retro_0.geometry} material={materials.Retro} />
                    <mesh name="Porte_avant_droite_Cr_Interieur_0" geometry={nodes.Porte_avant_droite_Cr_Interieur_0.geometry} material={materials.Cr_Interieur} />
                    <mesh name="Porte_avant_droite_Vitre_0" geometry={nodes.Porte_avant_droite_Vitre_0.geometry} material={materials.Vitre} />
                  </group>
                  <group name="Porti��re_avant_gauche" position={[128.821, -9.44, 342.127]}>
                    <mesh name="Porti��re_avant_gauche_Retro_0" geometry={nodes['Porti��re_avant_gauche_Retro_0'].geometry} material={materials.Retro} />
                    <mesh name="Porti��re_avant_gauche_Cr_Exterieur_0" geometry={nodes['Porti��re_avant_gauche_Cr_Exterieur_0'].geometry} material={materials.Cr_Exterieur} />
                    <mesh name="Porti��re_avant_gauche_Cr_Interieur_0" geometry={nodes['Porti��re_avant_gauche_Cr_Interieur_0'].geometry} material={materials.Cr_Interieur} />
                    <mesh name="Porti��re_avant_gauche_Vitre_0" geometry={nodes['Porti��re_avant_gauche_Vitre_0'].geometry} material={materials.Vitre} />
                  </group>
                  <group name="Symmetry" position={[-31.505, -14.582, -27.059]}>
                    <group name="Roue_2" position={[135.474, -142.506, -256.163]}>
                      <group name="Pneu_1" position={[-126.27, -247.215, 19.451]} rotation={[-0.428, 0, -Math.PI / 2]}>
                        <mesh name="Pneu_1_Pneu_0" geometry={nodes.Pneu_1_Pneu_0.geometry} material={materials.Pneu} />
                      </group>
                      <group name="Pneu" position={[-126.27, -247.215, 19.451]} rotation={[-0.428, 0, -Math.PI / 2]}>
                        <mesh name="Pneu_Pneu_0" geometry={nodes.Pneu_Pneu_0.geometry} material={materials.Pneu} />
                      </group>
                      <group name="Jante" position={[0.074, 0, 0.065]}>
                        <mesh name="Jante_Jante_2_0" geometry={nodes.Jante_Jante_2_0.geometry} material={materials.Jante_2} />
                      </group>
                    </group>
                  </group>
                  <group name="Roue_1_1" position={[-172.774, -157.088, 175.87]} rotation={[Math.PI, 0, Math.PI]}>
                    <group name="Jante_2" position={[-56.39, 71.253, -101.465]}>
                      <mesh name="Jante_2_Jante_0" geometry={nodes.Jante_2_Jante_0.geometry} material={materials.Jante} />
                    </group>
                    <group name="Pneu_2" position={[-141.344, -247.215, 19.321]} rotation={[-0.428, 0, -Math.PI / 2]}>
                      <mesh name="Pneu_2_Pneu_0" geometry={nodes.Pneu_2_Pneu_0.geometry} material={materials.Pneu} />
                    </group>
                  </group>
                  <group name="Roue_1" position={[113.839, -157.088, 175.87]}>
                    <group name="Jante_3" position={[-60.39, 71.253, -101.465]}>
                      <mesh name="Jante_3_Jante_0" geometry={nodes.Jante_3_Jante_0.geometry} material={materials.Jante} />
                    </group>
                    <group name="Pneu_3" position={[-145.344, -247.215, 19.321]} rotation={[-0.428, 0, -Math.PI / 2]}>
                      <mesh name="Pneu_3_Pneu_0" geometry={nodes.Pneu_3_Pneu_0.geometry} material={materials.Pneu} />
                    </group>
                  </group>
                  <group name="Essieu" position={[-42.869, -61.83, -114.846]}>
                    <mesh name="Essieu_Chassis_2_0" geometry={nodes.Essieu_Chassis_2_0.geometry} material={materials.Chassis_2} />
                  </group>
                  <group name="Interieur_3" position={[-0.739, 15.549, 31.182]}>
                    <mesh name="Interieur_3_Interieur_3_0" geometry={nodes.Interieur_3_Interieur_3_0.geometry} material={materials.Interieur_3} />
                  </group>
                  <group name="Interieur" position={[17.876, 53.947, 141.5]}>
                    <mesh name="Interieur_Interieur_4_0" geometry={nodes.Interieur_Interieur_4_0.geometry} material={materials.Interieur_4} />
                  </group>
                  <group name="Interieur_2" position={[21.457, 0.357, 110.466]}>
                    <mesh name="Interieur_2_Interieur_2_0" geometry={nodes.Interieur_2_Interieur_2_0.geometry} material={materials.Interieur_2} />
                  </group>
                  <group name="Retro" position={[-89.34, 15.291, 150.546]}>
                    <mesh name="Retro_Retro_0" geometry={nodes.Retro_Retro_0.geometry} material={materials.Retro} />
                  </group>
                  <group name="Barre" position={[-0.739, 15.549, 31.182]}>
                    <mesh name="Barre_Barre_0" geometry={nodes.Barre_Barre_0.geometry} material={materials.Barre} />
                  </group>
                  <group name="Autres" position={[-89.34, 15.291, 150.546]}>
                    <mesh name="Autres_Barre_0" geometry={nodes.Autres_Barre_0.geometry} material={materials.Barre} />
                  </group>
                  <group name="Vitre" position={[100.878, 97.888, 196.458]}>
                    <mesh name="Vitre_Vitre_0" geometry={nodes.Vitre_Vitre_0.geometry} material={materials.Vitre} />
                  </group>
                  <group name="Cordon" position={[-31.505, -14.582, -27.059]}>
                    <mesh name="Cordon_Cordon_0" geometry={nodes.Cordon_Cordon_0.geometry} material={materials.Cordon} />
                  </group>
                  <group name="Chassis_2" position={[-54.233, -109.078, -202.632]}>
                    <mesh name="Chassis_2_Chassis_2_0" geometry={nodes.Chassis_2_Chassis_2_0.geometry} material={materials.Chassis_2} />
                  </group>
                  <group name="Chassis" position={[-54.233, -109.078, -202.632]}>
                    <mesh name="Chassis_Chassis_0" geometry={nodes.Chassis_Chassis_0.geometry} material={materials.Chassis} />
                  </group>
                  <group name="Phare" position={[46.84, -13.367, -76.232]}>
                    <mesh name="Phare_Phare_0" geometry={nodes.Phare_Phare_0.geometry} material={materials.Phare} />
                  </group>
                  <group name="Cr_Interieur" position={[-13.991, 96.861, 223.641]}>
                    <mesh name="Cr_Interieur_Cr_Interieur_0" geometry={nodes.Cr_Interieur_Cr_Interieur_0.geometry} material={materials.Cr_Interieur} />
                  </group>
                  <group name="Cr_Exterieur" position={[8.495, 97.888, 222.109]}>
                    <mesh name="Cr_Exterieur_Cr_Exterieur_0" geometry={nodes.Cr_Exterieur_Cr_Exterieur_0.geometry} material={materials.Cr_Exterieur} />
                  </group>
                  <group name="Si��ge" position={[0.076, 14.602, 28.696]}>
                    <mesh name="Si��ge_Si��ge_0" geometry={nodes['Si��ge_Si��ge_0'].geometry} material={materials.Sige} />
                  </group>
                  <group name="Par_boue" position={[44.242, -86.924, -197.219]}>
                    <mesh name="Par_boue_Par_boue_0" geometry={nodes.Par_boue_Par_boue_0.geometry} material={materials.Par_boue} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../src/components/3dmodels/truck/truck.gltf')
